'use strict';

const CONFIG={boundariesUrl:'../data/geodata/bfa_admin1.json',organizationsUrl:'../data/odf/odf-organizations.json',center:[12.35,-1.55],zoom:6,minZoom:5,maxZoom:18,regionFields:['ADM1_FR','adm1NamNew','ADM1_NAME','NAME_1','shapeName','name'],oldRegionFields:['adm1NamOld','ADM1_OLD','OLD_NAME']};
const state={map:null,boundaries:null,boundaryLayer:null,markerLayer:null,legendControl:null,infoControl:null,organizations:[],filtered:[],selectedRegion:'',filters:{mode:'points',region:'',sector:'',funded:'',partner:''},regionCounts:new Map()};
const $=id=>document.getElementById(id);
const ui={map:$('odf-map'),form:$('odf-filter-form'),mapMode:$('map-mode'),region:$('filter-region'),sector:$('filter-sector'),funded:$('filter-funded'),partner:$('filter-partner'),reset:$('reset-filters'),status:$('map-status'),active:$('active-map-label'),kpis:$('odf-kpis'),table:$('odf-table-body'),summary:$('table-summary'),coverage:$('coverage-analysis'),funding:$('funding-analysis'),capacity:$('capacity-analysis'),sectors:$('sector-analysis')};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’']/g,'').replace(/[-_/]/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
const fmt=v=>new Intl.NumberFormat('fr-FR').format(Number(v)||0);
const arr=v=>Array.isArray(v)?v.map(x=>String(x).trim()).filter(Boolean):(v?String(v).split(/[,;|]/).map(x=>x.trim()).filter(Boolean):[]);
const bool=v=>typeof v==='boolean'?v:(typeof v==='number'?v===1:['true','oui','yes','1','vrai','y'].includes(norm(v)));
const coord=v=>{if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:null;};
const first=(o,keys,f='')=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&!(typeof v==='string'&&!v.trim()))return v;}return f;};
const unique=v=>[...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr',{sensitivity:'base'}));
const aliases=new Map([['kuilse','koulse'],['koulse','koulse'],['centre','kadiogo'],['centre nord','koulse'],['centre est','nakambe'],['centre ouest','nando'],['centre sud','nazinon'],['hauts bassins','guiriko'],['nord','yaadga'],['plateau central','oubri'],['sud ouest','djôrô'],['cascades','tannounyan']]);
const regionKey=v=>aliases.get(norm(v))||norm(v);
const sameRegion=(a,b)=>regionKey(a)===regionKey(b);
const setStatus=(m,t='info')=>{if(ui.status){ui.status.textContent=m;ui.status.dataset.status=t;}};

async function fetchJson(url){const r=await fetch(`${url}${url.includes('?')?'&':'?'}v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error(`${url} — erreur HTTP ${r.status}`);return r.json();}
function featureRegion(f){return String(first(f?.properties||{},CONFIG.regionFields,'')).trim();}
function featureOld(f){return String(first(f?.properties||{},CONFIG.oldRegionFields,'')).trim();}
function normalizeOrg(raw,i){const g=raw?.geometry?.type==='Point'&&Array.isArray(raw.geometry.coordinates)?raw.geometry.coordinates:[];const p=raw?.properties?{...raw.properties}:raw;const regions=arr(first(p,['regions','zones_intervention'],[]));const region=String(first(p,['region','région','Region','REGION','admin1','adm1','ADM1_FR'],regions[0]||'')).trim();return{id:String(first(p,['id','ID','code','organisation_id'],`ORG-${String(i+1).padStart(3,'0')}`)),name:String(first(p,['organisation','organization','name','nom','nom_organisation','acronyme'],`Organisation ${i+1}`)),region,regions:regions.length?regions:(region?[region]:[]),commune:String(first(p,['commune','Commune','ville','localite','localité'],'')),address:String(first(p,['adresse_generale','adresse','address'],'')),sectors:arr(first(p,['secteurs','sectors','sector','secteur','domaines_intervention','domaines'],[])),funded:bool(first(p,['financement_recent','financement','funded','recent_funding'],false)),partner:bool(first(p,['partenariat_humanitaire','partenaire','partner','intervient_reponse_humanitaire','participation_coordination'],false)),humanitarianResponse:bool(first(p,['intervient_reponse_humanitaire'],false)),coordination:bool(first(p,['participation_coordination'],false)),capacity:String(first(p,['capacite','capacité','capacity','niveau_capacite'],'Non renseigné')),latitude:coord(first(p,['latitude','lat','Latitude'],g[1])),longitude:coord(first(p,['longitude','lon','lng','Longitude'],g[0]))};}

function setupTabs(){const nav=$('subpage-nav');const toggle=document.querySelector('.subpage-menu-toggle');const panels=[...document.querySelectorAll('[data-dashboard-panel]')];const activate=id=>{const t=panels.find(p=>p.id===id)||panels[0];panels.forEach(p=>{const a=p===t;p.hidden=!a;p.classList.toggle('is-active',a);});document.querySelectorAll('[data-dashboard-target]').forEach(b=>b.classList.toggle('is-active',b.dataset.dashboardTarget===t.id));history.replaceState(null,'',`#${t.id}`);scrollTo({top:0,behavior:'smooth'});if(t.id==='carte'&&state.map)setTimeout(()=>state.map.invalidateSize(),180);};document.addEventListener('click',e=>{const b=e.target.closest('[data-dashboard-target]');if(!b)return;e.preventDefault();activate(b.dataset.dashboardTarget);nav?.classList.remove('open');});toggle?.addEventListener('click',()=>{const o=!nav.classList.contains('open');nav.classList.toggle('open',o);toggle.setAttribute('aria-expanded',String(o));});activate(location.hash.slice(1)||'vue-ensemble');}

async function loadData(){setStatus('Chargement des données…');const [b,o]=await Promise.all([fetchJson(CONFIG.boundariesUrl),fetchJson(CONFIG.organizationsUrl)]);if(b?.type!=='FeatureCollection'||!Array.isArray(b.features)||!b.features.length)throw new Error('bfa_admin1.json doit être un GeoJSON FeatureCollection non vide.');const rows=Array.isArray(o)?o:(o.organizations||o.organisations||o.features||[]);if(!rows.length)throw new Error('odf-organizations.json est vide.');state.boundaries=b;state.organizations=rows.map(normalizeOrg);state.filtered=[...state.organizations];}

function initMap(){if(typeof L==='undefined')throw new Error('Leaflet n’est pas chargé.');state.map=L.map(ui.map,{center:CONFIG.center,zoom:CONFIG.zoom,minZoom:CONFIG.minZoom,maxZoom:CONFIG.maxZoom,preferCanvas:true});const light=L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,subdomains:'abcd',attribution:'&copy; OpenStreetMap &copy; CARTO'}).addTo(state.map);const osm=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'});L.control.layers({'Fond clair':light,'OpenStreetMap':osm},{},{position:'topright',collapsed:true}).addTo(state.map);L.control.scale({metric:true,imperial:false}).addTo(state.map);const info=L.control({position:'topleft'});info.onAdd=()=>{info._div=L.DomUtil.create('div','map-info-control');info._div.innerHTML='<strong>Burkina Faso</strong><span>Survolez une région</span>';return info._div;};info.addTo(state.map);state.infoControl=info;}
const validCoord=o=>Number.isFinite(o.latitude)&&Number.isFinite(o.longitude)&&o.latitude>=8&&o.latitude<=16&&o.longitude>=-7&&o.longitude<=3;
function counts(){const m=new Map();state.boundaries.features.forEach(f=>{const r=featureRegion(f);if(r)m.set(r,0);});state.filtered.forEach(o=>{const r=[...m.keys()].find(x=>sameRegion(x,o.region));if(r)m.set(r,(m.get(r)||0)+1);});state.regionCounts=m;}
function countRegion(name){for(const [r,c] of state.regionCounts)if(sameRegion(r,name))return c;return 0;}
const color=c=>c>20?'#0b4f79':c>10?'#1683d8':c>5?'#58a9d8':c>2?'#9fd1ed':c>0?'#d8ecf8':'#e8edf1';
function boundaryStyle(f){const r=featureRegion(f);const s=state.selectedRegion&&sameRegion(r,state.selectedRegion);return{color:s?'#0b304a':'#61717f',weight:s?3:1.2,fillColor:state.filters.mode==='choropleth'?color(countRegion(r)):'#e6f2f9',fillOpacity:s?.9:(state.filters.mode==='choropleth'?.82:.4)};}
function updateInfo(r='',c=0){if(state.infoControl?._div)state.infoControl._div.innerHTML=r?`<strong>${esc(r)}</strong><span>${fmt(c)} ODF/ODDF</span>`:'<strong>Burkina Faso</strong><span>Survolez une région</span>';}
function selectRegion(name,layer){const opt=[...ui.region.options].find(o=>sameRegion(o.value,name));if(!opt)return;ui.region.value=opt.value;state.selectedRegion=opt.value;applyFilters(false);if(layer?.getBounds)state.map.fitBounds(layer.getBounds(),{padding:[30,30],maxZoom:9});}
function renderBoundaries(fit=true){if(state.boundaryLayer)state.map.removeLayer(state.boundaryLayer);state.boundaryLayer=L.geoJSON(state.boundaries,{style:boundaryStyle,onEachFeature:(f,l)=>{const r=featureRegion(f),old=featureOld(f),c=countRegion(r);l.bindTooltip(`<strong>${esc(r||'Région sans nom')}</strong>${old?`<br><span>Ancienne région : ${esc(old)}</span>`:''}<br>${fmt(c)} ODF/ODDF`,{sticky:true});l.bindPopup(`<div class="region-popup"><h3>${esc(r||'Région sans nom')}</h3><div class="popup-stat"><span>ODF/ODDF recensées</span><strong>${fmt(c)}</strong></div><button class="popup-filter-button" type="button" data-region="${esc(r)}">Filtrer cette région</button></div>`);l.on({mouseover:e=>{e.target.setStyle({weight:3,color:'#0b304a',fillOpacity:.95});e.target.bringToFront();updateInfo(r,c);},mouseout:e=>{state.boundaryLayer.resetStyle(e.target);updateInfo();},click:e=>selectRegion(r,e.target)});}}).addTo(state.map);const b=state.boundaryLayer.getBounds();if(fit&&b.isValid())state.map.fitBounds(b,{padding:[18,18]});}
function popup(o){const loc=o.commune||o.address||'Non renseignée';return`<div class="organization-popup"><p class="popup-eyebrow">ODF/ODDF</p><h3>${esc(o.name)}</h3><dl><div><dt>Région</dt><dd>${esc(o.region||'Non renseignée')}</dd></div><div><dt>Localisation</dt><dd>${esc(loc)}</dd></div><div><dt>Secteurs</dt><dd>${esc(o.sectors.join(', ')||'Non renseigné')}</dd></div><div><dt>Financement</dt><dd>${o.funded?'Oui':'Non'}</dd></div><div><dt>Réponse humanitaire</dt><dd>${o.humanitarianResponse?'Oui':'Non'}</dd></div><div><dt>Coordination</dt><dd>${o.coordination?'Oui':'Non'}</dd></div></dl></div>`;}
function renderMarkers(){if(state.markerLayer)state.map.removeLayer(state.markerLayer);state.markerLayer=L.layerGroup();if(state.filters.mode!=='points')return;const groups=new Map();state.filtered.forEach(o=>{if(!validCoord(o))return;const k=`${o.latitude.toFixed(5)}|${o.longitude.toFixed(5)}`;const i=groups.get(k)||0;groups.set(k,i+1);const a=i*2.3999632297,r=Math.min(.18,.018*Math.sqrt(i));const m=L.circleMarker([o.latitude+Math.sin(a)*r,o.longitude+Math.cos(a)*r],{radius:6,color:'#fff',weight:2,fillColor:'#5a2a84',fillOpacity:.95});m.bindTooltip(esc(o.name),{direction:'top'});m.bindPopup(popup(o),{maxWidth:360});m.addTo(state.markerLayer);});state.markerLayer.addTo(state.map);}
function renderLegend(){if(state.legendControl)state.map.removeControl(state.legendControl);const legend=L.control({position:'bottomright'});legend.onAdd=()=>{const d=L.DomUtil.create('div','map-legend');if(state.filters.mode==='points')d.innerHTML='<h4>Légende</h4><div class="legend-row"><span class="legend-point"></span><span>ODF/ODDF géolocalisée approximativement</span></div><div class="legend-row"><span class="legend-area"></span><span>Limite régionale</span></div>';else d.innerHTML='<h4>Nombre d’ODF/ODDF</h4>'+[['0','#e8edf1'],['1–2','#d8ecf8'],['3–5','#9fd1ed'],['6–10','#58a9d8'],['11–20','#1683d8'],['21+','#0b4f79']].map(([l,c])=>`<div class="legend-row"><span class="legend-swatch" style="background:${c}"></span><span>${l}</span></div>`).join('');return d;};legend.addTo(state.map);state.legendControl=legend;}
function populate(select,values,label){select.innerHTML=`<option value="">${label}</option>`+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');}
function populateFilters(){populate(ui.region,unique([...state.boundaries.features.map(featureRegion),...state.organizations.map(o=>o.region)]),'Toutes les régions');populate(ui.sector,unique(state.organizations.flatMap(o=>o.sectors)),'Tous les secteurs');}
function readFilters(){state.filters={mode:ui.mapMode.value||'points',region:ui.region.value,sector:ui.sector.value,funded:ui.funded.value,partner:ui.partner.value};state.selectedRegion=state.filters.region;}
function filter(){state.filtered=state.organizations.filter(o=>(!state.filters.region||o.regions.some(r=>sameRegion(r,state.filters.region)))&&(!state.filters.sector||o.sectors.some(s=>norm(s)===norm(state.filters.sector)))&&(state.filters.funded===''||o.funded===(state.filters.funded==='true'))&&(state.filters.partner===''||o.partner===(state.filters.partner==='true')));}
function renderKpis(){const total=state.filtered.length,geo=state.filtered.filter(validCoord).length,funded=state.filtered.filter(o=>o.funded).length,partners=state.filtered.filter(o=>o.partner).length,regions=unique(state.filtered.flatMap(o=>o.regions).map(regionKey)).length;ui.kpis.innerHTML=[[total,'ODF/ODDF correspondant aux filtres',`${fmt(geo)} géolocalisée(s)`],[regions,'Régions couvertes','Présence territoriale'],[funded,'ODF/ODDF récemment financées',total?`${Math.round(funded/total*100)} %`:'0 %'],[partners,'Partenaires humanitaires',total?`${Math.round(partners/total*100)} %`:'0 %']].map(([v,l,d])=>`<article class="kpi-card"><span class="kpi-label">${l}</span><strong class="kpi-value">${fmt(v)}</strong><span class="kpi-detail">${d}</span></article>`).join('');}
const renderList=(el,items)=>{el.innerHTML=items.map(x=>`<li>${esc(x)}</li>`).join('');};
function renderAnalysis(){const ranked=[...state.regionCounts].sort((a,b)=>b[1]-a[1]),covered=ranked.filter(([,c])=>c>0),blank=ranked.filter(([,c])=>c===0),lead=covered[0];renderList(ui.coverage,[lead?`${lead[0]} présente le plus grand nombre d’ODF/ODDF (${fmt(lead[1])}).`:'Aucune organisation ne correspond aux filtres.',`${fmt(covered.length)} région(s) couverte(s).`,`${fmt(blank.length)} région(s) sans organisation visible.`]);const funded=state.filtered.filter(o=>o.funded).length,hr=state.filtered.filter(o=>o.humanitarianResponse).length,coord=state.filtered.filter(o=>o.coordination).length;renderList(ui.funding,[`${fmt(funded)} ODF/ODDF ont déclaré un financement récent.`,`${fmt(hr)} interviennent dans la réponse humanitaire.`,`${fmt(coord)} participent à un mécanisme de coordination.`]);const cap=new Map(),sec=new Map();state.filtered.forEach(o=>{cap.set(o.capacity||'Non renseigné',(cap.get(o.capacity||'Non renseigné')||0)+1);o.sectors.forEach(s=>sec.set(s,(sec.get(s)||0)+1));});renderList(ui.capacity,[...cap].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=>`${k} : ${fmt(v)} organisation(s).`));renderList(ui.sectors,[...sec].sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k,v])=>`${k} : ${fmt(v)} organisation(s).`));}
function renderTable(){const rows=[...state.filtered].sort((a,b)=>a.name.localeCompare(b.name,'fr',{sensitivity:'base'}));ui.table.innerHTML=rows.length?rows.map(o=>`<tr><td><strong>${esc(o.name)}</strong></td><td>${esc(o.region||'Non renseignée')}</td><td>${esc(o.commune||o.address||'Non renseignée')}</td><td>${esc(o.sectors.join(', ')||'Non renseigné')}</td><td><span class="status-badge ${o.funded?'status-yes':'status-no'}">${o.funded?'Oui':'Non'}</span></td><td><span class="status-badge ${o.partner?'status-yes':'status-no'}">${o.partner?'Oui':'Non'}</span></td></tr>`).join(''):'<tr><td colspan="6" class="table-empty">Aucune organisation ne correspond aux filtres.</td></tr>';ui.summary.textContent=`${fmt(rows.length)} organisation(s) affichée(s).`;}
function refresh(fit=true){counts();renderBoundaries(fit);renderMarkers();renderLegend();renderKpis();renderAnalysis();renderTable();ui.active.textContent=ui.mapMode.options[ui.mapMode.selectedIndex]?.textContent.trim()||'Cartographie des ODF/ODDF';setStatus(state.filters.mode==='points'?`${fmt(state.filtered.filter(validCoord).length)} ODF/ODDF affichée(s) sur la carte.`:`${fmt(state.filtered.length)} ODF/ODDF agrégée(s) par région.`,'success');state.map.invalidateSize();}
function applyFilters(fit=true){readFilters();filter();refresh(fit);}
function bind(){ui.form.addEventListener('submit',e=>{e.preventDefault();applyFilters();});ui.reset.addEventListener('click',()=>{ui.mapMode.value='points';ui.region.value='';ui.sector.value='';ui.funded.value='';ui.partner.value='';state.selectedRegion='';applyFilters();});[ui.mapMode,ui.region,ui.sector,ui.funded,ui.partner].forEach(el=>el.addEventListener('change',()=>applyFilters()));document.addEventListener('click',e=>{const b=e.target.closest('.popup-filter-button');if(!b)return;const o=[...ui.region.options].find(x=>sameRegion(x.value,b.dataset.region||''));if(o){ui.region.value=o.value;applyFilters(false);}state.map.closePopup();});addEventListener('resize',()=>state.map?.invalidateSize());}
function fail(error){console.error(error);setStatus(error.message,'error');ui.kpis.innerHTML=`<article class="kpi-card"><span class="kpi-label">Erreur de chargement</span><strong class="kpi-value">—</strong><span class="kpi-detail">${esc(error.message)}</span></article>`;ui.map.innerHTML=`<div class="map-error"><strong>La carte ne peut pas être affichée.</strong><p>${esc(error.message)}</p></div>`;ui.table.innerHTML=`<tr><td colspan="6" class="table-empty">${esc(error.message)}</td></tr>`;}
addEventListener('DOMContentLoaded',async()=>{try{setupTabs();initMap();await loadData();populateFilters();bind();readFilters();filter();refresh();setStatus(`${fmt(state.organizations.length)} ODF/ODDF chargée(s).`,'success');}catch(error){fail(error);}});
